export const IADJ =[
    { Kanji: "青い", Furigana: "あおい", Romaji: "aoi", Meaning: "blue" },
    { Kanji: "赤い", Furigana: "あかい", Romaji: "akai", Meaning: "red" },
    { Kanji: "明るい", Furigana: "あかるい", Romaji: "akarui", Meaning: "light, bright" },
    { Kanji: "温かい", Furigana: "あたたかい", Romaji: "atatakai", Meaning: "warm" },
    { Kanji: "新しい", Furigana: "あたらしい", Romaji: "atarashii", Meaning: "new" },
    { Kanji: "暑い", Furigana: "あつい", Romaji: "atsui", Meaning: "hot (air)" },
    { Kanji: "厚い", Furigana: "あつい", Romaji: "atsui", Meaning: "thick" },
    { Kanji: "危ない", Furigana: "あぶない", Romaji: "abunai", Meaning: "dangerous" },
    { Kanji: "甘い", Furigana: "あまい", Romaji: "amai", Meaning: "sweet" },
    { Kanji: "良い", Furigana: "よい / いい", Romaji: "yoi / ii", Meaning: "good" },
    { Kanji: "忙しい", Furigana: "いそがしい", Romaji: "isogashii", Meaning: "to be busy" },
    { Kanji: "痛い", Furigana: "いたい", Romaji: "itai", Meaning: "to be painful" },
    { Kanji: "薄い", Furigana: "うすい", Romaji: "usui", Meaning: "thin" },
    { Kanji: "美味しい", Furigana: "おいしい", Romaji: "oishii", Meaning: "tasty, delicious" },
    { Kanji: "大きい", Furigana: "おおきい", Romaji: "ookii", Meaning: "big" },
    { Kanji: "遅い", Furigana: "おそい", Romaji: "osoi", Meaning: "late, slow" },
    { Kanji: "重い", Furigana: "おもい", Romaji: "omoi", Meaning: "heavy" },
    { Kanji: "面白い", Furigana: "おもしろい", Romaji: "omoshiroi", Meaning: "interesting, funny" },
    { Kanji: "辛い", Furigana: "からい", Romaji: "karai", Meaning: "hot, spicy" },
    { Kanji: "軽い", Furigana: "かるい", Romaji: "karui", Meaning: "light (not heavy)" },
    { Kanji: "可愛い", Furigana: "かわいい", Romaji: "kawaii", Meaning: "cute, pretty" },
    { Kanji: "黄色い", Furigana: "きいろい", Romaji: "kiiroi", Meaning: "yellow" },
    { Kanji: "汚い", Furigana: "きたない", Romaji: "kitanai", Meaning: "dirty" },
    { Kanji: "暗い", Furigana: "くらい", Romaji: "kurai", Meaning: "dark" },
    { Kanji: "黒い", Furigana: "くろい", Romaji: "kuroi", Meaning: "black" },
    { Kanji: "寒い", Furigana: "さむい", Romaji: "samui", Meaning: "cold" },
    { Kanji: "白い", Furigana: "しろい", Romaji: "shiroi", Meaning: "white" },
    { Kanji: "涼しい", Furigana: "すずしい", Romaji: "suzushii", Meaning: "cool" },
    { Kanji: "狭い", Furigana: "せまい", Romaji: "semai", Meaning: "narrow" },
    { Kanji: "高い", Furigana: "たかい", Romaji: "takai", Meaning: "high, expensive" },
    { Kanji: "楽しい", Furigana: "たのしい", Romaji: "tanoshii", Meaning: "pleasant, enjoyable" },
    { Kanji: "小さい", Furigana: "ちいさい", Romaji: "chiisai", Meaning: "small" },
    { Kanji: "近い", Furigana: "ちかい", Romaji: "chikai", Meaning: "near, close" },
    { Kanji: "詰らない", Furigana: "つまらない", Romaji: "tsumaranai", Meaning: "uninteresting" },
    { Kanji: "冷たい", Furigana: "つめたい", Romaji: "tsumetai", Meaning: "cold" },
    { Kanji: "強い", Furigana: "つよい", Romaji: "tsuyoi", Meaning: "strong" },
    { Kanji: "遠い", Furigana: "とおい", Romaji: "tooi", Meaning: "far" },
    { Kanji: "長い", Furigana: "ながい", Romaji: "nagai", Meaning: "long" },
    { Kanji: "早い", Furigana: "はやい", Romaji: "hayai", Meaning: "early" },
    { Kanji: "速い", Furigana: "はやい", Romaji: "hayai", Meaning: "fast, quick" },
    { Kanji: "低い", Furigana: "ひくい", Romaji: "hikui", Meaning: "low" },
    { Kanji: "広い", Furigana: "ひろい", Romaji: "hiroi", Meaning: "wide, spacious" },
    { Kanji: "太い", Furigana: "ふとい", Romaji: "futoi", Meaning: "thick, fat" },
    { Kanji: "古い", Furigana: "ふるい", Romaji: "furui", Meaning: "old" },
    { Kanji: "欲しい", Furigana: "ほしい", Romaji: "hoshii", Meaning: "to want something" },
    { Kanji: "細い", Furigana: "ほそい", Romaji: "hosoi", Meaning: "thin, fine" },
    { Kanji: "不味い", Furigana: "まずい", Romaji: "mazui", Meaning: "bad tasting" },
    { Kanji: "丸い", Furigana: "まるい", Romaji: "marui", Meaning: "round" },
    { Kanji: "短い", Furigana: "みじかい", Romaji: "mijikai", Meaning: "short" },
    { Kanji: "難しい", Furigana: "むずかしい", Romaji: "muzukashii", Meaning: "difficult" },
    { Kanji: "優しい", Furigana: "やさしい", Romaji: "yasashii", Meaning: "gentle" },
    { Kanji: "安い", Furigana: "やすい", Romaji: "yasui", Meaning: "cheap" },
    { Kanji: "若い", Furigana: "わかい", Romaji: "wakai", Meaning: "young" }
  ]
  