export const Naadj = [
    { "Kanji": "好き", "Furigana": "すき", "Romaji": "Suki", "Meaning": "Like, love" },
    { "Kanji": "結構", "Furigana": "けっこう", "Romaji": "Kekkou", "Meaning": "wonderful, enviable" },
    { "Kanji": "有名", "Furigana": "ゆうめい", "Romaji": "Yuumei", "Meaning": "Famous" },
    { "Kanji": "きれい", "Furigana": "きれい", "Romaji": "Kirei", "Meaning": "Pretty, beautiful" },
    { "Kanji": "丁寧", "Furigana": "ていねい", "Romaji": "Teinei", "Meaning": "polite" },
    { "Kanji": "嫌い", "Furigana": "きらい", "Romaji": "Kirai", "Meaning": "to not like" },
    { "Kanji": "静か", "Furigana": "しずか", "Romaji": "Shizuka", "Meaning": "quiet" },
    { "Kanji": "暇", "Furigana": "ひま", "Romaji": "Hima", "Meaning": "free (time)" },
    { "Kanji": "賑やか", "Furigana": "にぎやか", "Romaji": "Nigiyaka", "Meaning": "lively" },
    { "Kanji": "便利", "Furigana": "べんり", "Romaji": "Benri", "Meaning": "useful, convenient" },
    { "Kanji": "元気", "Furigana": "げんき", "Romaji": "Genki", "Meaning": "healthy" },
    { "Kanji": "色々", "Furigana": "いろいろ", "Romaji": "Iroiro", "Meaning": "various" },
    { "Kanji": "大丈夫", "Furigana": "だいじょうぶ", "Romaji": "Daijoubu", "Meaning": "OK, fine" },
    { "Kanji": "丈夫", "Furigana": "じょうぶ", "Romaji": "Joubu", "Meaning": "Healthy, robust" },
    { "Kanji": "大変", "Furigana": "たいへん", "Romaji": "Taihen", "Meaning": "Terrible" },
    { "Kanji": "楽", "Furigana": "らく", "Romaji": "Raku", "Meaning": "comfortable, easy" },
    { "Kanji": "いや", "Furigana": "いや", "Romaji": "Iya", "Meaning": "unpleasant" },
    { "Kanji": "大切", "Furigana": "たいせつ", "Romaji": "Taisetsu", "Meaning": "important, precious" },
    { "Kanji": "上手", "Furigana": "じょうず", "Romaji": "Jyouzu", "Meaning": "good, skilled" },
    { "Kanji": "下手", "Furigana": "へた", "Romaji": "Heta", "Meaning": "bad at, unskilled" },
    { "Kanji": "一生懸命", "Furigana": "いっしょうけんめい", "Romaji": "Isshoukenmei", "Meaning": "to one’s fullest possibility" },
    { "Kanji": "危険", "Furigana": "きけん", "Romaji": "Kiken", "Meaning": "Dangerous" },
    { "Kanji": "残念", "Furigana": "ざんねん", "Romaji": "Zannen", "Meaning": "regrettable, disappointing" },
    { "Kanji": "心配", "Furigana": "しんぱい", "Romaji": "Shinpai", "Meaning": "care, worry" },
    { "Kanji": "自由", "Furigana": "じゆう", "Romaji": "Jiyuu", "Meaning": "free, unrestrained" },
    { "Kanji": "十分", "Furigana": "じゅうぶん", "Romaji": "Jyuubun", "Meaning": "sufficient" },
    { "Kanji": "大好き", "Furigana": "だいすき", "Romaji": "Daisuki", "Meaning": "Passionate" },
    { "Kanji": "適当", "Furigana": "てきとう", "Romaji": "Tekitou", "Meaning": "proper, suitable" },
    { "Kanji": "特別", "Furigana": "とくべつ", "Romaji": "Tokubetsu", "Meaning": "special" },
    { "Kanji": "熱心", "Furigana": "ねっしん", "Romaji": "Nesshin", "Meaning": "eager, enthusiastic" },
    { "Kanji": "必要", "Furigana": "ひつよう", "Romaji": "Hitsuyou", "Meaning": "necessary" },
    { "Kanji": "まじめ", "Furigana": "まじめ", "Romaji": "Majime", "Meaning": "serious, earnest" },
    { "Kanji": "真直ぐ", "Furigana": "まっすぐ", "Romaji": "Massugu", "Meaning": "straight" },
    { "Kanji": "無理", "Furigana": "むり", "Romaji": "Muri", "Meaning": "unreasonable" },
    { "Kanji": "立派", "Furigana": "りっぱ", "Romaji": "Rippa", "Meaning": "Excellent, splendid, fine" }
  ]
  