export const Verbs = [
    { "Kanji": "会う", "Furigana": "あう", "Romaji": "au", "Meaning": "to meet", "Type": "Verb" },
    { "Kanji": "開く", "Furigana": "あく", "Romaji": "aku", "Meaning": "to open", "Type": "Verb" },
    { "Kanji": "開ける", "Furigana": "あける", "Romaji": "akeru", "Meaning": "to open", "Type": "Verb" },
    { "Kanji": "あげる", "Furigana": "あげる", "Romaji": "ageru", "Meaning": "to give", "Type": "Verb" },
    { "Kanji": "遊ぶ", "Furigana": "あそぶ", "Romaji": "asobu", "Meaning": "to play", "Type": "Verb" },
    { "Kanji": "浴びる", "Furigana": "あびる", "Romaji": "abiru", "Meaning": "to take a shower", "Type": "Verb" },
    { "Kanji": "洗う", "Furigana": "あらう", "Romaji": "arau", "Meaning": "to wash", "Type": "Verb" },
    { "Kanji": "有る", "Furigana": "ある", "Romaji": "aru", "Meaning": "to exist", "Type": "Verb" },
    { "Kanji": "ある", "Furigana": "ある", "Romaji": "aru", "Meaning": "to possess", "Type": "Verb" },
    { "Kanji": "歩く", "Furigana": "あるく", "Romaji": "aruku", "Meaning": "to walk", "Type": "Verb" },
    { "Kanji": "言う", "Furigana": "いう", "Romaji": "iu", "Meaning": "to say, to tell", "Type": "Verb" },
    { "Kanji": "行く", "Furigana": "いく", "Romaji": "iku", "Meaning": "to go", "Type": "Verb" },
    { "Kanji": "いる", "Furigana": "いる", "Romaji": "iru", "Meaning": "to exist", "Type": "Verb" },
    { "Kanji": "入れる", "Furigana": "いれる", "Romaji": "ireru", "Meaning": "to insert, to put in", "Type": "Verb" },
    { "Kanji": "歌う", "Furigana": "うたう", "Romaji": "utau", "Meaning": "to sing", "Type": "Verb" },
    { "Kanji": "生まれる", "Furigana": "うまれる", "Romaji": "umareru", "Meaning": "to be born", "Type": "Verb" },
    { "Kanji": "売る", "Furigana": "うる", "Romaji": "uru", "Meaning": "to sell", "Type": "Verb" },
    { "Kanji": "起きる", "Furigana": "おきる", "Romaji": "okiru", "Meaning": "to get up, to stand up", "Type": "Verb" },
    { "Kanji": "送る", "Furigana": "おくる", "Romaji": "okuru", "Meaning": "to send", "Type": "Verb" },
    { "Kanji": "押す", "Furigana": "おす", "Romaji": "osu", "Meaning": "to push", "Type": "Verb" },
    { "Kanji": "覚える", "Furigana": "おぼえる", "Romaji": "oboeru", "Meaning": "to memorize, to remember", "Type": "Verb" },
    { "Kanji": "泳ぐ", "Furigana": "およぐ", "Romaji": "oyogu", "Meaning": "to swim", "Type": "Verb" },
    { "Kanji": "降りる", "Furigana": "おりる", "Romaji": "oriru", "Meaning": "to get off", "Type": "Verb" },
    { "Kanji": "終わる", "Furigana": "おわる", "Romaji": "owaru", "Meaning": "to end", "Type": "Verb" },
    { "Kanji": "買う", "Furigana": "かう", "Romaji": "kau", "Meaning": "to buy", "Type": "Verb" },
    { "Kanji": "返す", "Furigana": "かえす", "Romaji": "kaesu", "Meaning": "to return an object", "Type": "Verb" },
    { "Kanji": "帰る", "Furigana": "かえる", "Romaji": "kaeru", "Meaning": "to return home", "Type": "Verb" },
    { "Kanji": "書く", "Furigana": "かく", "Romaji": "kaku", "Meaning": "to write", "Type": "Verb" },
    { "Kanji": "貸す", "Furigana": "かす", "Romaji": "kasu", "Meaning": "to lend", "Type": "Verb" },
    { "Kanji": "借りる", "Furigana": "かりる", "Romaji": "kariru", "Meaning": "to borrow", "Type": "Verb" },
    { "Kanji": "聞く", "Furigana": "きく", "Romaji": "kiku", "Meaning": "to listen", "Type": "Verb" },
    { "Kanji": "切る", "Furigana": "きる", "Romaji": "kiru", "Meaning": "to cut", "Type": "Verb" },
    { "Kanji": "着る", "Furigana": "きる", "Romaji": "kiru", "Meaning": "to wear, to put on", "Type": "Verb" },
    { "Kanji": "来る", "Furigana": "くる", "Romaji": "kuru", "Meaning": "to come", "Type": "Verb" },
    { "Kanji": "消す", "Furigana": "けす", "Romaji": "kesu", "Meaning": "to turn off, to switch off", "Type": "Verb" },
    { "Kanji": "答える", "Furigana": "こたえる", "Romaji": "kotaeru", "Meaning": "to answer", "Type": "Verb" },
    { "Kanji": "困る", "Furigana": "こまる", "Romaji": "komaru", "Meaning": "to be in trouble", "Type": "Verb" },
    { "Kanji": "咲く", "Furigana": "さく", "Romaji": "saku", "Meaning": "to blossom", "Type": "Verb" },
    { "Kanji": "死ぬ", "Furigana": "しぬ", "Romaji": "shinu", "Meaning": "to die, to pass away", "Type": "Verb" },
    { "Kanji": "閉める", "Furigana": "しめる", "Romaji": "shimeru", "Meaning": "to close", "Type": "Verb" },
    { "Kanji": "知る", "Furigana": "しる", "Romaji": "shiru", "Meaning": "to know", "Type": "Verb" },
    { "Kanji": "する", "Furigana": "する", "Romaji": "suru", "Meaning": "to do", "Type": "Verb" },
    { "Kanji": "食べる", "Furigana": "たべる", "Romaji": "taberu", "Meaning": "to eat", "Type": "Verb" },
    { "Kanji": "使う", "Furigana": "つかう", "Romaji": "tsukau", "Meaning": "to use", "Type": "Verb" },
    { "Kanji": "寝る", "Furigana": "ねる", "Romaji": "neru", "Meaning": "to sleep", "Type": "Verb" },
    { "Kanji": "読む", "Furigana": "よむ", "Romaji": "yomu", "Meaning": "to read", "Type": "Verb" }
  ]
  